---
title: "Malaga Horarios"
author: "Danyu"
date: "3/11/2021"
output: word_document
---

```{r}
library(ggplot2)
library(dplyr)
library(readxl)
library(stringr)
```



OCTUBRE
```{r}
df_monthly <- list.files(path="C:/Users/Beatriz Garcia/Desktop/DANYU/ECI/ECI_OCT/data_modified", full.names = TRUE) %>% 
  lapply(read.csv2) %>% 
  bind_rows 

df_monthly$Precio = as.numeric(df_monthly$Precio)

df_monthly$hora <- str_sub(df_monthly$horaOperacion, -5,-4)
df_monthly$hora <- as.numeric(df_monthly$hora) 

df_malaga <- df_monthly[df_monthly$Punto.de.Venta.Centro == df_monthly$Punto.de.Venta.Centro[131],]
df_malaga$dia <- as.character(str_sub(df_malaga$Fecha, 9,10))

weekday <- rep(seq(1,7,1),6)[5:35]
dia <- seq(01,31,1)
dia <- as.character(dia)
dia <- ifelse(nchar(dia)!=2,paste0("0",dia),dia)
dfaux <- data.frame(weekday, dia)


df_malaga <- left_join(df_malaga, dfaux, by = "dia")
```

```{r}
df_malaga %>% group_by(Operacion, weekday, dia) %>% summarise(precioTicket = sum(Precio)) %>% 
  group_by(weekday) %>% summarise(count=n())
```
```{r}
m1 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==1) %>% 
  filter(hora>=0) 

m11 <- m1 %>% group_by(hora) %>% summarise(count= n())
m11$porcentaje <- m11$count/sum(m11$count)

m11 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "pink") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en el Lunes")


#table(m1$hora)
#m1 %>% ggplot() +
#  geom_histogram(aes(as.factor(hora)), stat = "count", fill = "pink") +
#  ggtitle("Horas Puntas Malaga en ls Lunes")
```


```{r}
m2 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==2) %>% 
  filter(hora>=0) 

m21 <- m2 %>% group_by(hora) %>% summarise(count= n())
m21$porcentaje <- m21$count/sum(m21$count)

m21 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "plum2") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1)+
  ggtitle("Horas Puntas Malaga en el Martes") 


#df_malaga %>% group_by(Operacion, a, dia, hora) %>% 
#  summarise(precioTicket = sum(Precio)) %>% 
#  filter(a==2) %>% 
#  filter(hora>=0) %>% 
#  ggplot() +
#  geom_histogram(aes(as.factor(hora)), stat = "count", fill = "pink") +
#  ggtitle("Horas Puntas Malaga en ls Martes") 
```

```{r}
m3 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==3) %>% 
  filter(hora>=0) 

m31 <- m3 %>% group_by(hora) %>% summarise(count= n())
m31$porcentaje <- m31$count/sum(m31$count)

m31 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue1") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en el Miercoles")
```


```{r}
m4 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==4) %>% 
  filter(hora>=0) 

m41 <- m4 %>% group_by(hora) %>% summarise(count= n())
m41$porcentaje <- m41$count/sum(m41$count)

m41 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "seagreen3") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en el Jueves")
```

```{r}
m5 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==5) %>% 
  filter(hora>=0) 

m51 <- m5 %>% group_by(hora) %>% summarise(count= n())
m51$porcentaje <- m51$count/sum(m51$count)

m51 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "lightsalmon1") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en el Viernes")
```

```{r}
m6 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==6) %>% 
  filter(hora>=0) 

m61 <- m6 %>% group_by(hora) %>% summarise(count= n())
m61$porcentaje <- m61$count/sum(m61$count)

m61 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "lightsteelblue2") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en el Sabado")
```

```{r}
df1 <- as.data.frame(table(m1$hora))
names(df1) <- c("Hora", "nº tickets lunes")
df2 <- as.data.frame(table(m2$hora))
names(df2) <- c("Hora", "nº tickets martes")
df3 <- as.data.frame(table(m3$hora))
names(df3) <- c("Hora", "nº tickets miercoles")
df4 <- as.data.frame(table(m4$hora))
names(df4) <- c("Hora", "nº tickets jueves")
df5 <- as.data.frame(table(m5$hora))
names(df5) <- c("Hora", "nº tickets viernes")
df6 <- as.data.frame(table(m6$hora))
names(df6) <- c("Hora", "nº tickets sabado")


df<- df1 %>% merge(df2,by = "Hora", all = TRUE) %>% 
  merge(df3,by = "Hora", all = TRUE) %>% 
  merge(df4,by = "Hora", all = TRUE) %>% 
  merge(df5,by = "Hora", all = TRUE) %>% 
  merge(df6,by = "Hora", all = TRUE)
```






SEPTIEMBRE
```{r}
df_monthly2 <- list.files(path="C:/Users/Beatriz Garcia/Desktop/DANYU/ECI_SEP/data_modified", full.names = TRUE) %>% 
  lapply(read.csv2) %>% 
  bind_rows 

df_monthly2$Precio = as.numeric(df_monthly2$Precio)

df_monthly2$hora <- str_sub(df_monthly2$horaOperacion, -5,-4)
df_monthly2$hora <- as.numeric(df_monthly2$hora) 

df_malaga9 <- df_monthly2[df_monthly2$Punto.de.Venta.Centro == df_monthly2$Punto.de.Venta.Centro[170],]
df_malaga9$dia <- as.character(str_sub(df_malaga9$Fecha, 9,10))

weekday <- rep(seq(1,7,1),5)[3:32]
dia <- seq(01,30,1)
dia <- as.character(dia)
dia <- ifelse(nchar(dia)!=2,paste0("0",dia),dia)
dfaux <- data.frame(weekday, dia)


df_malaga9 <- left_join(df_malaga9, dfaux, by = "dia")
```

```{r}
df_malaga9 %>% group_by(Operacion, weekday, dia) %>% summarise(precioTicket = sum(Precio)) %>% 
  group_by(weekday) %>% summarise(count=n())
```
```{r}
m91 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==1) %>% 
  filter(hora>=0)
m92 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==2) %>% 
  filter(hora>=0) 
m93 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==3) %>% 
  filter(hora>=0) 
m94 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==4) %>% 
  filter(hora>=0) 
m95 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==5) %>% 
  filter(hora>=0) 
m96 <- df_malaga %>% group_by(Operacion, weekday, dia, hora) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==6) %>% 
  filter(hora>=0) 
```


```{r}
df11 <- as.data.frame(table(m91$hora))
names(df11) <- c("Hora", "nº tickets lunes")
df22 <- as.data.frame(table(m92$hora))
names(df22) <- c("Hora", "nº tickets martes")
df33 <- as.data.frame(table(m93$hora))
names(df33) <- c("Hora", "nº tickets miercoles")
df44 <- as.data.frame(table(m94$hora))
names(df44) <- c("Hora", "nº tickets jueves")
df55 <- as.data.frame(table(m95$hora))
names(df55) <- c("Hora", "nº tickets viernes")
df66 <- as.data.frame(table(m96$hora))
names(df66) <- c("Hora", "nº tickets sabado")


df9<- df11 %>% merge(df22,by = "Hora", all = TRUE) %>% 
  merge(df33,by = "Hora", all = TRUE) %>% 
  merge(df44,by = "Hora", all = TRUE) %>% 
  merge(df55,by = "Hora", all = TRUE) %>% 
  merge(df66,by = "Hora", all = TRUE)
```


```{r}
malaga <- rbind(df_malaga, df_malaga9)
malaga$mes <- str_sub(malaga$Fecha, 6,7)
```


```{r} 
# malaga1 %>% ggplot() +
#   geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
#   ggtitle("Horas Puntas Malaga en el Lunes")+ 
#   labs(x = "Hora", y = "Count")
```

```{r}
malaga1 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
 summarise(precioTicket = sum(Precio)) %>% 
 filter(weekday==1) %>% 
 filter(hora>=0)

malaga1 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  ggtitle("Horas Puntas Malaga en el Lunes")+ 
  labs(x = "Hora", y = "Count") +
  facet_wrap(~mes)
```


```{r}
malaga2 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==2) %>% 
  filter(hora>=0) 


malaga2 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  facet_grid(~mes)+
  labs(x = "Hora", y = "Count") +
  ggtitle("Horas Puntas Malaga en el Martes")
```

```{r}
malaga3 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==3) %>% 
  filter(hora>=0) 


malaga3 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  facet_grid(~mes) +
  labs(x = "Hora", y = "Count") +
  ggtitle("Horas Puntas Malaga en el Miercoles")
```



```{r}
malaga4 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==4) %>% 
  filter(hora>=0) 


malaga4 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  facet_grid(~mes) +
  labs(x = "Hora", y = "Count") +
  ggtitle("Horas Puntas Malaga en el Jueves")
```



```{r}
malaga5 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==5) %>% 
  filter(hora>=0) 


malaga5 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  facet_grid(~mes) +
  labs(x = "Hora", y = "Count") +
  ggtitle("Horas Puntas Malaga en el Viernes")
```



```{r}
malaga6 <- malaga %>% group_by(Operacion, weekday, dia, hora, mes) %>% 
  summarise(precioTicket = sum(Precio)) %>% 
  filter(weekday==6) %>% 
  filter(hora>=0) 


malaga6 %>% ggplot() +
  geom_histogram(aes(as.factor(hora), fill = as.factor(mes)), stat = "count") +
  labs(x = "Hora", y = "Count") +
  facet_grid(~mes) +4
  ggtitle("Horas Puntas Malaga en el Sabado")
```







```{r}
m911 <- m91 %>% group_by(hora) %>% summarise(count= n())
m911$porcentaje <- m911$count/sum(m911$count)

m911 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "pink") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en ls Lunes")


#table(m1$hora)
#m1 %>% ggplot() +
#  geom_histogram(aes(as.factor(hora)), stat = "count", fill = "pink") +
#  ggtitle("Horas Puntas Malaga en ls Lunes")
```


```{r}
m921 <- m92 %>% group_by(hora) %>% summarise(count= n())
m921$porcentaje <- m921$count/sum(m921$count)

m921 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "plum2") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1)+
  ggtitle("Horas Puntas Malaga en ls Martes") 


#df_malaga %>% group_by(Operacion, a, dia, hora) %>% 
#  summarise(precioTicket = sum(Precio)) %>% 
#  filter(a==2) %>% 
#  filter(hora>=0) %>% 
#  ggplot() +
#  geom_histogram(aes(as.factor(hora)), stat = "count", fill = "pink") +
#  ggtitle("Horas Puntas Malaga en ls Martes") 
```

```{r}
m931 <- m93 %>% group_by(hora) %>% summarise(count= n())
m931$porcentaje <- m931$count/sum(m931$count)

m931 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "skyblue1") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en ls Miercoles")
```


```{r}
m941 <- m94 %>% group_by(hora) %>% summarise(count= n())
m941$porcentaje <- m941$count/sum(m941$count)

m941 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "seagreen3") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en ls Jueves")
```

```{r}
m951 <- m95 %>% group_by(hora) %>% summarise(count= n())
m951$porcentaje <- m951$count/sum(m951$count)

m951 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "lightsalmon1") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en ls Viernes")
```

```{r}
m961 <- m96 %>% group_by(hora) %>% summarise(count= n())
m961$porcentaje <- m961$count/sum(m961$count)

m961 %>% ggplot(aes(as.factor(hora), y = count)) +
  geom_bar(stat = "identity", fill = "lightsteelblue2") + 
  labs(x = "Hora", y = "Count") +
  theme(text = element_text(size=10)) +
  geom_text(aes(label = scales::percent(porcentaje), 
                  y = porcentaje),
              position = position_dodge(width = 0.9),
              vjust = -1) +
  ggtitle("Horas Puntas Malaga en ls Sabado")
```










algunas cosillas
```{r}
dfm20 <- df_malaga[df_malaga$hora==20,]
dfm20$dia <- as.character(str_sub(dfm20$horaOperacion, 1,2))

dfm20$mins <- str_sub(dfm20$horaOperacion, 15,16)
dfm20 %>% ggplot() +
  geom_histogram(aes(mins), stat="count", fill = "pink")

table(dfm20$dia)


dfm14 <- df_malaga[df_malaga$hora==14,]
dfm14$dia <- as.character(str_sub(dfm14$horaOperacion, 1,2))

dfm14$mins <- str_sub(dfm14$horaOperacion, 15,16)
dfm14 %>% ggplot() +
  geom_histogram(aes(mins), stat="count", fill = "pink")

table(dfm14$dia)




dfm14 <- left_join(dfm14, dfaux, by = "dia")
dfm20 <- left_join(dfm20, dfaux, by = "dia")

table(dfm14$a)
table(dfm20$a)

dfm14[dfm14$a == 6,]$mins

dfm14[dfm14$a == 6,] %>% ggplot() +
  geom_histogram(aes(mins), stat = "count", fill = "pink")

dfm20[dfm20$a == 6,] %>% ggplot() +
  geom_histogram(aes(mins), stat = "count", fill = "pink")
```
